source 'https://rubygems.org'
ruby '2.2.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'
gem 'puma'

# Front-end app controller
gem 'foreman'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use background process (for cron)
gem 'whenever', require: false

# Use debugger
# gem 'debugger', group: [:development, :test]

# Exception notification for Errbit
gem 'airbrake'

# Use devise for sign up & sign in
gem 'devise', '~> 3.4.0'

# Use Omniauth
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'

# Use paperclip with Amazon-S3
gem 'paperclip', '~> 4.2'
gem 'aws-sdk', '< 2.0'

# Rails I18n de-facto standard library for ActiveRecord model/data translation
gem 'globalize', '~> 5.0.0'
gem 'globalize-accessors'

# Use acts-as-taggable-on for Tag management
gem 'acts-as-taggable-on', '~> 3.4'

# for bulk-insert
gem 'activerecord-import'

# Use Slim template for views.
gem 'slim-rails'

# Compass
gem 'compass-rails'

# Twitter Bootstrap
gem 'bootstrap-sass', '~> 3.2.0'

# Use for meta tag
gem 'meta-tags', require: 'meta_tags'

# NewRelic
gem 'newrelic_rpm'

# For font-awesome
gem 'font-awesome-rails'

# Pagenation
gem 'kaminari'

# Colored output to console
gem 'colored'

# Management Screen
gem 'activeadmin', '~> 1.0.0.pre1'

# CSV file import for ActiveAdmin
gem 'active_admin_importable'

# retina_tag
gem 'retina_tag'

# Use settingslogic for constants and enviromental values
gem 'settingslogic'

# twitter api
gem 'twitter'

# Page title
gem 'title'

# Test send mail in mode development
gem "letter_opener", :group => :development

# from rails-assets.org
source 'https://rails-assets.org' do
  gem 'rails-assets-infinite-scroll'
  gem 'rails-assets-underscore'
  gem 'rails-assets-jquery-cookie'
  gem 'rails-assets-jQuery.mmenu'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.1'
  gem 'spring-commands-rspec'
  gem 'shoulda-matchers', require: false
  # pry
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'pry-byebug'
  # trace process to debug
  gem 'rbtrace'
end

group :development do
  # Debugger in Rails 4.2
  gem 'web-console', '~> 2.0'
  gem 'better_errors'
  gem 'binding_of_caller'
  # Time measurement of rendering
  gem 'rack-mini-profiler'
  # Schema information
  gem 'annotate'
end

group :test do
  gem 'database_cleaner'
end

group :production, :staging, :beta do
  gem 'rails_12factor'
end
