defaults: &defaults
  button_points:
    going_again: 14
    been_there : -5
    wish_to_go : 1
  limit_of_click: 999
  counts_per_page: 10
  counts_per_page_for_ad: 2
  btn_status_size: 3
  max_rank: 100
  unread_counts: 10
  badge_counts:
    gold: 3
    silver: 2
    bronze: 1
  twitter:
    # NOTE: (twitter制限140文字) - (体験リンク23文字) - (画像リンク23文字)
    max_text_length: 94
  language_switch:
    en: English
    ja: 日本語
    ko: 한국어
    th: ไทย
  user_score:
    # NOTE: ユーザースコア加減算基準値
    reference_value:
      login:
        term_of_bonus: 7
      click_wish_to_go:
        - 1
        - 10
        - 30
        - 100
      click_been_there:
        - 1
        - 3
        - 5
      upload_photo:
        - 1
        - 5
        - 10
        - 30
      pinned_photo:
        - 1
        - 10
        - 30
        - 100
      followed:
        - 1
        - 10
        - 30
        - 100
        - 1000
      following:
        - 1
        - 3
        - 5
        - 10
      activated_exp_by_click:
        - 10
        - 100
        - 1000
      activated_exp_by_modifying:
        percentage: 5
        period: 1
    # NOTE: ユーザースコア加減算ポイント
    bonus_points:
      login: 10
      click_wish_to_go:
        - 5
        - 5
        - 5
        - 5
      click_been_there:
        - 5
        - 5
        - 5
      upload_photo:
        - 5
        - 5
        - 5
        - 5
      pinned_photo:
        - 5
        - 5
        - 5
        - 5
      followed:
        - 5
        - 5
        - 5
        - 5
        - 5
      following:
        - 5
        - 5
        - 5
        - 5
      activated_exp_by_click:
        - 1
        - 2
        - 3
      activated_exp_by_modifying: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults

beta:
  <<: *defaults
